name: 'tf_easyurl'

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_STATE_RG: ${{ secrets.TF_STATE_RG }}
      TF_STATE_SA: ${{ secrets.TF_STATE_SA }}
      TF_STATE_CN: ${{ secrets.TF_STATE_CN }}
      TF_STATE_FILE: ${{ secrets.TF_STATE_FILE }}

    runs-on: ubuntu-latest
    environment: production
     
    defaults:
      run:
        shell: bash
    steps:
        - name: Checkout
          uses: actions/checkout@v3      
        
        - name: Terraform_Setup
          uses: hashicorp/setup-terraform@v2

        - name: Terraform_Init
          run: terraform init -backend-config=storage_account_name=$TF_STATE_SA -backend-config=container_name=$TF_STATE_CN -backend-config=key=$TF_STATE_FILE -backend-config=resource_group_name=$TF_STATE_RG -backend-config=subscription_id="$ARM_SUBSCRIPTION_ID" -backend-config=tenant_id="$ARM_TENANT_ID" -backend-config=client_id="$ARM_CLIENT_ID" -backend-config=client_secret="$ARM_CLIENT_SECRET"

        - name: Terraform_Plan
          run: terraform plan -var="ARM_CLIENT_ID=$ARM_CLIENT_ID" -var="ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET" -var="ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID" -var="ARM_TENANT_ID=$ARM_TENANT_ID" 

        - name: Terraform_Apply
          run: terraform apply -input=false -auto-approve -var="ARM_CLIENT_ID=$ARM_CLIENT_ID" -var="ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET" -var="ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID" -var="ARM_TENANT_ID=$ARM_TENANT_ID" 
