name: 'tf_easyurl'

on:
  workflow_dispatch:
    inputs:
      TFAction:
        description: "Terraform Action - Apply or Destroy"     
        required: true
        default: "apply"

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_STATE_RG: ${{ secrets.TF_STATE_RG }}
      TF_STATE_SA: ${{ secrets.TF_STATE_SA }}
      TF_STATE_CN: ${{ secrets.TF_STATE_CN }}
      TF_STATE_FILE: ${{ secrets.TF_STATE_FILE }}
    runs-on: ubuntu-latest
    environment: production
     
    defaults:
      run:
        shell: bash
    steps:
        - name: Checkout
          uses: actions/checkout@v3      
        
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2

        - name: Terraform Init
          run: terraform init -backend-config=storage_account_name=$TF_STATE_SA -backend-config=container_name=$TF_STATE_CN -backend-config=key=$TF_STATE_FILE -backend-config=resource_group_name=$TF_STATE_RG -backend-config=subscription_id="$ARM_SUBSCRIPTION_ID" -backend-config=tenant_id="$ARM_TENANT_ID" -backend-config=client_id="$ARM_CLIENT_ID" -backend-config=client_secret="$ARM_CLIENT_SECRET"

        - name: Terraform Plan
          run: terraform plan -var="ARM_CLIENT_ID=$ARM_CLIENT_ID" -var="ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET" -var="ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID" -var="ARM_TENANT_ID=$ARM_TENANT_ID" 

        - name: Terraform Apply
          if: ${{ inputs.TFAction == 'apply'}}  
          run: terraform apply -input=false -auto-approve -var="ARM_CLIENT_ID=$ARM_CLIENT_ID" -var="ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET" -var="ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID" -var="ARM_TENANT_ID=$ARM_TENANT_ID" 

        - name: Terraform Destroy
          if: ${{ inputs.TFAction == 'destroy' }} 
          run: terraform destroy -input=false -auto-approve -var="ARM_CLIENT_ID=$ARM_CLIENT_ID" -var="ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET" -var="ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID" -var="ARM_TENANT_ID=$ARM_TENANT_ID" 